// Generated by CoffeeScript 1.4.0
(function() {
  var events;

  events = [
    {
      Title: "Five K for charity",
      Date: new Date("12/13/2012")
    }, {
      Title: "Dinner",
      Date: new Date("12/25/2012")
    }, {
      Title: "Meeting with manager",
      Date: new Date("12/01/2012")
    }, {
      Title: "Meeting with manager2",
      Date: new Date("12/01/2012")
    }
  ];

  $(function() {
    var highlightDaysWithEvents, homeTabs;
    homeTabs = $(".slidetabs").tabs(".slides > .slide", {
      effect: 'fade',
      fadeOutSpeed: "slow",
      rotate: true,
      tabs: 'div.slidetab'
    }).slideshow();
    highlightDaysWithEvents = function(date) {
      var matching, result;
      result = [true, '', null];
      matching = $.grep(events, function(event) {
        return event.Date.valueOf() === date.valueOf();
      });
      if (matching.length) {
        result = [true, 'highlight', null];
      }
      return result;
    };
    return $("div.calendar").datepicker({
      inline: true,
      showOtherMonths: true,
      dayNamesMin: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
      beforeShowDay: highlightDaysWithEvents
    });
  });

}).call(this);
