// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var addPopUp, getMonthEvents, highlightDaysWithEvents, homeTabs, showDayEvents, _updateDatepicker_o;
    homeTabs = $(".slidetabs").tabs(".slides > .slide", {
      effect: 'fade',
      fadeOutSpeed: "slow",
      rotate: true,
      tabs: 'div.slidetab'
    }).slideshow();
    getMonthEvents = function(year, month) {
      return [
        {
          Title: "Blue Man Group",
          category: "Theater",
          Date: new Date("12/13/2012")
        }, {
          Title: "Dinner",
          category: "Gallery",
          Date: new Date("12/13/2012")
        }, {
          Title: "Dinner 2",
          category: "Gallery",
          Date: new Date("12/23/2012")
        }
      ];
    };
    _updateDatepicker_o = $.datepicker._updateDatepicker;
    $.datepicker._updateDatepicker = function(instance) {
      _updateDatepicker_o.apply(this, [instance]);
      return addPopUp(instance.drawYear, instance.drawMonth + 1, instance.id);
    };
    addPopUp = function(year, month, calendarId) {
      var cells;
      cells = $("#" + calendarId).find("td.highlight");
      return cells.each(function(index, elem) {
        var $elem, events, matching;
        $elem = $(elem);
        events = getMonthEvents($elem.data("year"), $elem.data("month"));
        matching = $.grep(events, function(event) {
          return parseInt(event.Date.getDate().valueOf()) === parseInt($elem.children("a").text().valueOf());
        });
        $elem.children("a").data("evnts", matching);
        return $elem.children("a").on("click", function(event) {
          event.preventDefault();
          return console.log($(this).data("evnts"));
        });
      });
    };
    highlightDaysWithEvents = function(date) {
      var events, matching, result;
      result = [true, '', null];
      events = getMonthEvents(date.getFullYear(), date.getMonth());
      matching = $.grep(events, function(event) {
        return event.Date.valueOf() === date.valueOf();
      });
      if (matching.length) {
        result = [true, 'highlight', null];
      }
      return result;
    };
    showDayEvents = function(dateText) {
      var date;
      date = new Date(dateText);
      return console.log(date);
    };
    return $("div.calendar").datepicker({
      inline: true,
      showOtherMonths: true,
      dayNamesMin: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
      beforeShowDay: highlightDaysWithEvents,
      onSelect: showDayEvents
    });
  });

}).call(this);
